BMXUTL6	; IHS/OIT/HMW - BMXNET INSTALLATION CALLS ;
	;;2.2;BMX;;Sep 07, 2010
	;
	;
POST	;EP - Called from BMX Installation postinit
	;
	;Add BMX AV CODE to XUS SIGNON broker option
	N BMXFDA,BMXIEN,BMXMSG,BMXIENS,BMXMENN,BMXAVI
	S BMXAVI=$O(^XWB(8994,"B","BMX AV CODE",0))
	Q:'+BMXAVI
	S BMXIENS=$O(^DIC(19,"B","XUS SIGNON",0))
	Q:'+BMXIENS
	;
	S BMXIENS="?+2,"_BMXIENS_","
	S BMXFDA(19.05,BMXIENS,.01)=BMXAVI
	K BMXIEN,BMXMSG
	S DIC(0)=""
	D UPDATE^DIE("","BMXFDA","BMXIEN","BMXMSG")
	Q
	;
	;
	;
	;Create BMXNET,APPLICATION user and set attributes
	;
	;N BMXFDA,BMXIEN,BMXMSG,BMXIENS,BMXMENN
	;S BMXIENS = "?+1,"
	;S BMXFDA(200,BMXIENS,.01)="BMXNET,APPLICATION"
	;S BMXFDA(200,BMXIENS,2)="1_(a>yr}:3x3ja9\8vbH"
	;S BMXFDA(200,BMXIENS,11)="$;HOSs|:3w25lLD}Be="
	;S BMXFDA(200,BMXIENS,11.2)="88888,88888"
	;S BMXMENN=$O(^DIC(19,"B","BMXRPC",0))
	;I +BMXMENN S BMXFDA(200.03,"?+2,?+1,",.01)=BMXMENN
	;K BMXIEN,BMXMSG
	;S DIC(0)=""
	;D UPDATE^DIE("","BMXFDA","BMXIEN","BMXMSG")
	Q
